apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2019-05-22T01:09:20Z
  generation: 2
  labels:
    run: postgres
  name: postgres
  namespace: default
  resourceVersion: "159251"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/postgres
  uid: 3a9dd426-7c2e-11e9-b158-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          value: memes
        - name: POSTGRES_PASSWORD
          value: redditmemes
        image: postgres
        imagePullPolicy: Always
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-05-22T01:09:20Z
    lastUpdateTime: 2019-05-22T01:09:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-05-22T01:09:20Z
    lastUpdateTime: 2019-05-24T01:26:32Z
    message: ReplicaSet "postgres-686b6b57d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
